# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34d56f145c6bedf11fa25a66cce5319fa888963a92eb190782eb6238b44f102cd37a5f13d5e3f0b7a0905153e1bd2f413c66ac4936340846dda7ee7aebca325

test:
  secret_key_base: b32d8f8dde28186fddbc142b7be072b88c4a675a98a10146d83b5528a470c5771f128bf82f84d3bd54dd16da83147f1b2efdf33cf515da62f370aafc942e12a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
